### ISSUE TITLE
support deep group of compound selectors

### ISSUE THREAD

**Issue by barak007** [wixplosives/tokey#143]
currently we have only shallow support we want to have deep compound selectors for nested cases

**Comment by danieleww** [comment]
I think I'll go with this simple solution:

https://github.com/wixplosives/component-studio/pull/8925/files#diff-52ac72702570230e7bff4836a204f679ae642860e6b91a47539e33816e4f23dcR157

About pseudo-elements:

"Only one pseudo-element may appear per selector, and if present it must appear after the sequence of simple selectors that represents the [subjects](https://www.w3.org/TR/2018/REC-selectors-3-20181106/#subject) of the selector. Note: A future version of this specification may allow multiple pseudo-elements per selector."
https://www.w3.org/TR/2018/REC-selectors-3-20181106/

Also, the CSS validator for version 3 accepts multiple pseudo-elements not only at the end, for example:
`div.foo::before.bar::after {}`

Opinions?

**Comment by barak007** [comment]
@ido

This selector is weird `div.foo::before.bar::after {}` and also [not working](https://jsbin.com/jupenec/1/edit?html,css,js,output)

**Comment by ido** [comment]
Cool project, wrong Ido. :smile:
